name: Stream Robot Warriors Battle Live

on:
  push:
    branches: ["**/**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99
      CF_STREAM_KEY: ${{ secrets.CF_STREAM_KEY }}
      CF_PLAYER_URL: ${{ secrets.CF_PLAYER_URL }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install --disable-pip-version-check --no-cache-dir machfs

      - name: Build .dsk (CI template + battle script)
        run: |
          mkdir -p build
          python scripts/build_disk.py \
            --template "images/Robot Warriors CI.dsk" \
            --robots-dir robots \
            --write-battle-script \
            --out build/robot.dsk
          ls -lh build

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11vnc basilisk2 ffmpeg

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          limit-access-to-actor: true

      - name: Start Xvfb on :99
        run: |
          Xvfb :99 -screen 0 512x342x24 -ac > /tmp/Xvfb.log 2>&1 &
          for i in {1..20}; do
            [ -S /tmp/.X11-unix/X99 ] && break
            echo "Waiting for Xvfb..."
            sleep 0.3
          done

      - name: Run battle using headless Basilisk II and push to stream
        working-directory: build
        timeout-minutes: 20
        run: |
          ROM="${GITHUB_WORKSPACE}/images/Mac_IIci.ROM"
          IMG="${PWD}/robot.dsk"

          ffmpeg \
            -f x11grab -draw_mouse 0 -video_size 512x342 -framerate 60 \
            -use_wallclock_as_timestamps 1 -thread_queue_size 1024 \
            -i :99 -vf "format=gray,fps=30" \
            -c:v libx264 -preset ultrafast -tune zerolatency \
            -profile:v baseline -level 3.1 -pix_fmt yuv420p \
            -b:v 800k -maxrate 800k -bufsize 1200k \
            -x264-params "keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr" \
            -r 30 -g 30 \
            -f flv "rtmps://live.cloudflare.com:443/live/$CF_STREAM_KEY" \
            -loglevel error &
          FF_PID=$!

          BasiliskII \
              --delay 10000 \
              --cpu 3 \
              --fpu true \
              --nogui true \
              --disk "${IMG}" \
              --rom "${ROM}" || true

          kill -INT "$FF_PID" || true
          wait "$FF_PID" || true
